{{- if .Values.quarto.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarto
  labels:
    app: quarto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarto
  template:
    metadata:
      labels:
        app: quarto
    spec:
      containers:
        - name: quarto
          image: "{{ .Values.quarto.image.repository }}:{{ .Values.quarto.image.tag }}"
          imagePullPolicy: {{ .Values.quarto.image.pullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quarto
spec:
  selector:
    app: quarto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{- end }}
