apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.local.dev`) && (PathPrefix(`/ui/v2/login`) || PathPrefix(`/ui/login/v2`))
      kind: Rule
      priority: 100
      services:
        - name: srdp-zitadel-login
          port: 3000
    - match: Host(`auth.local.dev`)
      kind: Rule
      services:
        - name: srdp-zitadel
          port: 8080
          scheme: h2c
  tls:
    secretName: custom-ingress-cert