apiVersion: v2
name: srdp-chart
description: Umbrella chart for SRDP Platform (Traefik + Zitadel + Oauth2Proxy + Apps)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: traefik
    version: 37.4.0
    repository: https://traefik.github.io/charts
  
  - name: zitadel
    version: 9.13.0
    repository: https://charts.zitadel.com

  - name: postgresql
    version: 18.1.11
    repository: https://charts.bitnami.com/bitnami
    alias: zitadel-db
    
  - name: oauth2-proxy
    version: 9.0.0
    repository: https://oauth2-proxy.github.io/manifests